const fs=require('fs'),path=require('path'),vm=require('vm');
const repo=process.argv[2]||path.resolve(__dirname,'..');
let total=0,failed=0;function ok(v,m){total++;if(!v){failed++;console.error('FAIL '+m)}}function eq(a,b,m){ok(JSON.stringify(a)===JSON.stringify(b),m+' expected='+JSON.stringify(b)+' actual='+JSON.stringify(a))}
function storageFor(map){return {getItem:k=>map.has(k)?map.get(k):null,setItem:(k,v)=>map.set(k,String(v)),removeItem:k=>map.delete(k)}}
function context(extra={},sharedLocal){const sessionMap=new Map(),localMap=sharedLocal||new Map();const sessionStorage=storageFor(sessionMap),localStorage=storageFor(localMap);const window={sessionStorage,localStorage,...extra};const ctx={window,console,Date,Object,Array,String,Number,Boolean,Math,JSON,RegExp,Error,Uint8Array,AbortController,setTimeout,clearTimeout,encodeURIComponent};vm.createContext(ctx);for(const f of ['js/live-room/remote/live-room-contract.js','js/live-room/remote/live-room-client.js'])vm.runInContext(fs.readFileSync(path.join(repo,f),'utf8'),ctx);return {ctx,window,sessionMap,localMap}}
function response(request,data,error){return {protocolVersion:'1.0',operation:request.operation,requestId:request.requestId,success:!error,data:error?null:data,error:error||null}}
const iso='2026-08-13T20:00:00.000Z',exp='2026-08-13T20:10:00.000Z';function room(id='room-1'){return {roomId:id,campaignId:'campaign-1',publicationId:'pub-1',createdAt:iso,lastActivityAt:iso,expiresAt:exp,status:'active'}}function presence(id='room-1',p='host-1',role='host'){return {roomId:id,participantId:p,role,joinedAt:iso,lastSeenAt:iso}}function roster(){return {generatedAt:iso,registeredParticipantCount:2,activeParticipantCount:2,activePlayerCount:1,hostConnected:true,participants:[{participantId:'host-1',role:'host',joinedAt:iso,lastSeenAt:iso,connected:true},{participantId:'player-1',role:'player',joinedAt:iso,lastSeenAt:iso,connected:true}]}}
const token='c'.repeat(64);let calls=[];let lastCapability='';
const {window}=context();const contract=window.CRIOS_REMOTE_LIVE_ROOM_CONTRACT;const api=window.CRIOS_REMOTE_LIVE_ROOM_CLIENT;
const fetchImpl=async(_url,init)=>{calls.push(init);const env=JSON.parse(init.body),req=env.liveRoomRequest;lastCapability=req.payload.capabilityToken||'';let data;if(req.operation==='getLiveRoom')data={room:room(req.payload.roomId)};else if(req.operation==='getLiveRoomRoster')data={room:room(req.payload.roomId),roster:roster()};else if(req.operation==='joinLiveRoom')data={room:room(req.payload.roomId),presence:presence(req.payload.roomId,req.payload.participantId,'player')};else if(req.operation==='heartbeatLiveRoom')data={room:room(req.payload.roomId),presence:presence(req.payload.roomId,req.payload.participantId,'player')};else data={room:room('room-created'),presence:presence('room-created',req.payload.participantId,'host')};return {ok:true,status:200,text:async()=>JSON.stringify(response(req,data,null))}};
let rid=0;const client=api.createClient({contract,endpoint:'https://example.test/exec',fetchImpl,requestIdFactory:op=>'req-'+op+'-'+(++rid),capabilityFactory:()=>token});
ok(client.available(),'available');ok(Object.isFrozen(client),'client frozen');ok(api.version==='1.2.0','api version');
(async()=>{
let r=await client.createLiveRoom('campaign-1','pub-1','host-1');ok(r.success,'create success');eq(r.data.room.roomId,'room-created','created room id');ok(lastCapability===token,'create capability sent');ok(!JSON.stringify(r).includes(token),'create result secret-free');ok(calls[0].method==='POST','post transport');eq(Object.keys(JSON.parse(calls[0].body)),['liveRoomRequest'],'dedicated envelope');
r=await client.heartbeatLiveRoom('room-created','host-1');ok(r.success,'heartbeat uses stored token');ok(lastCapability===token,'stored capability recovered');
const hostPersistence=context({},new Map());const persistentClient=hostPersistence.window.CRIOS_REMOTE_LIVE_ROOM_CLIENT.createClient({contract:hostPersistence.window.CRIOS_REMOTE_LIVE_ROOM_CONTRACT,endpoint:'https://example.test/exec',fetchImpl,requestIdFactory:()=> 'persist-create',capabilityFactory:()=>token});
r=await persistentClient.createLiveRoom('campaign-1','pub-1','host-persist');ok(r.success,'persistent host create success');eq(hostPersistence.localMap.size,1,'host capability stored persistently');eq(hostPersistence.sessionMap.size,1,'host capability mirrored to session');
const reopenedContext=context({},hostPersistence.localMap);const reopenedClient=reopenedContext.window.CRIOS_REMOTE_LIVE_ROOM_CLIENT.createClient({contract:reopenedContext.window.CRIOS_REMOTE_LIVE_ROOM_CONTRACT,endpoint:'https://example.test/exec',fetchImpl,requestIdFactory:()=> 'persist-reopen',capabilityFactory:()=>token});
r=await reopenedClient.heartbeatLiveRoom('room-created','host-persist');ok(r.success,'host capability recovered after tab close simulation');eq(reopenedContext.sessionMap.size,1,'persistent host capability rehydrated into session');

r=await client.getLiveRoom('room-created');ok(r.success,'get success');ok(!calls[calls.length-1].body.includes('capabilityToken'),'get no capability');
r=await client.getLiveRoomRoster('room-created','host-1');ok(r.success,'host roster success');eq(r.data.roster.activePlayerCount,1,'roster active player count');ok(lastCapability===token,'roster uses stored host capability');ok(calls[calls.length-1].body.includes('getLiveRoomRoster'),'roster operation sent');ok(!JSON.stringify(r).includes(token),'roster result secret-free');
r=await client.joinLiveRoom('room-created','player-1');ok(r.success,'join success');eq(r.data.presence.role,'player','join role');r=await client.heartbeatLiveRoom('room-created','player-1');ok(r.success,'player heartbeat stored credential');
const playerPersistence=context({},new Map());const playerPersistentClient=playerPersistence.window.CRIOS_REMOTE_LIVE_ROOM_CLIENT.createClient({contract:playerPersistence.window.CRIOS_REMOTE_LIVE_ROOM_CONTRACT,endpoint:'https://example.test/exec',fetchImpl,requestIdFactory:()=> 'player-persist',capabilityFactory:()=>token});
r=await playerPersistentClient.joinLiveRoom('room-created','player-session-only');ok(r.success,'player join for persistence boundary');eq(playerPersistence.localMap.size,0,'player capability not persisted across tab close');eq(playerPersistence.sessionMap.size,1,'player capability remains session scoped');

ok(client.forgetCapability('room-created','player-1'),'forget credential');r=await client.heartbeatLiveRoom('room-created','player-1');ok(!r.success&&r.error.code==='CAPABILITY_STORAGE_UNAVAILABLE','forgotten heartbeat fails closed');r=await client.getLiveRoomRoster('room-created','player-1');ok(!r.success&&r.error.code==='CAPABILITY_STORAGE_UNAVAILABLE','forgotten roster fails closed before network');

const noCrypto=context().window;const noCryptoClient=noCrypto.CRIOS_REMOTE_LIVE_ROOM_CLIENT.createClient({contract:noCrypto.CRIOS_REMOTE_LIVE_ROOM_CONTRACT,endpoint:'https://x',fetchImpl,requestIdFactory:()=> 'r'});r=await noCryptoClient.createLiveRoom('campaign-1','pub-1','host');ok(!r.success&&r.error.code==='CAPABILITY_GENERATION_UNAVAILABLE','no crypto fails secure generation');

const badStore={get:()=>'',set:()=>false,remove:()=>false};const badStoreClient=api.createClient({contract,endpoint:'https://x',fetchImpl,credentialStore:badStore,requestIdFactory:()=> 'store-r',capabilityFactory:()=>token});r=await badStoreClient.createLiveRoom('campaign-1','pub-1','host-store');ok(!r.success&&r.error.code==='CAPABILITY_STORAGE_UNAVAILABLE','storage failure surfaced');ok(r.error.metadata.roomCreated===true,'storage failure marks server room created');

const serverErrorFetch=async(_u,init)=>{const req=JSON.parse(init.body).liveRoomRequest;return {ok:true,status:200,text:async()=>JSON.stringify(response(req,null,{code:req.operation==='getLiveRoomRoster'?'HOST_REQUIRED':'ROOM_EXPIRED',message:req.operation==='getLiveRoomRoster'?'Only the LiveRoom host can read the participant roster.':'Esta sesión finalizó por inactividad.',retryable:false}))}};const ec=api.createClient({contract,endpoint:'https://x',fetchImpl:serverErrorFetch,requestIdFactory:()=> 'err-r',capabilityFactory:()=>token,credentialStore:{get:()=>token,set:()=>true,remove:()=>true}});r=await ec.getLiveRoom('room-1');ok(!r.success&&r.error.code==='ROOM_EXPIRED','server error propagated');eq(r.error.message,'Esta sesión finalizó por inactividad.','expiry message preserved');r=await ec.getLiveRoomRoster('room-1','host-1');ok(!r.success&&r.error.code==='HOST_REQUIRED','roster host-required propagated');

const httpClient=api.createClient({contract,endpoint:'https://x',fetchImpl:async()=>({ok:false,status:429,text:async()=>''}),requestIdFactory:()=> 'http-r',capabilityFactory:()=>token});r=await httpClient.getLiveRoom('room');ok(!r.success&&r.error.code==='LIVE_ROOM_HTTP_ERROR','http error');ok(r.error.retryable,'429 retryable');
const brokenJson=api.createClient({contract,endpoint:'https://x',fetchImpl:async()=>({ok:true,status:200,text:async()=>'{bad'}),requestIdFactory:()=> 'json-r',capabilityFactory:()=>token});r=await brokenJson.getLiveRoom('room');ok(!r.success&&r.error.code==='LIVE_ROOM_RESPONSE_PARSE_FAILED','bad json');
const unavailable=api.createClient({contract:null,endpoint:'',fetchImpl:null});ok(!unavailable.available(),'unavailable');r=await unavailable.getLiveRoom('room');ok(!r.success&&r.error.code==='LIVE_ROOM_CLIENT_UNAVAILABLE','unavailable result');
const invalid=api.createClient({contract,endpoint:'https://x',fetchImpl,requestIdFactory:()=> 'invalid-r',capabilityFactory:()=>token,credentialStore:{get:()=>token,set:()=>true,remove:()=>true}});r=await invalid.getLiveRoom('');ok(!r.success&&r.error.code==='INVALID_REQUEST','invalid room local reject');r=await invalid.getLiveRoomRoster('','host-1');ok(!r.success&&r.error.code==='INVALID_REQUEST','invalid roster room local reject');r=await invalid.getLiveRoomRoster('room-1','');ok(!r.success&&r.error.code==='INVALID_REQUEST','invalid roster participant local reject');

const sharedCredentialStore={get:()=>token,set:()=>true,setPersistent:()=>true,remove:()=>true};let siblingOptions=null;
const siblingFactory={createClient:options=>{siblingOptions=options;return Object.freeze({available:()=>true,marker:'game-state-sibling'})}};
const siblingParent=api.createClient({contract,endpoint:'https://sibling.test/exec',fetchImpl,credentialStore:sharedCredentialStore,timeoutMs:4321,gameStateContract:{marker:'state-contract'},gameStateModel:{marker:'state-model'},gameStateClientFactory:siblingFactory});
const siblingContext={roomId:'room-created',campaignId:'campaign-1',publicationId:'pub-1',participantId:'player-1',missionOrder:['energy']};
const sibling=siblingParent.createGameStateClient(siblingContext);
ok(Boolean(sibling)&&sibling.marker==='game-state-sibling','game-state sibling created');
ok(siblingOptions.context===siblingContext,'sibling receives exact context reference for its own validation');
ok(siblingOptions.credentialStore===sharedCredentialStore,'sibling receives same credential store instance');
ok(siblingOptions.fetchImpl===fetchImpl,'sibling reuses transport implementation');
eq(siblingOptions.endpoint,'https://sibling.test/exec','sibling reuses endpoint');eq(siblingOptions.timeoutMs,4321,'sibling reuses timeout');
ok(!Object.keys(siblingParent).includes('getCapability'),'parent exposes no capability getter');
ok(client.createGameStateClient(siblingContext)===null,'missing optional state modules fail closed');

ok(typeof client.getLiveRoomRoster==='function','roster method exposed');ok(!Object.keys(client).includes('deleteLiveRoom'),'no delete method');ok(!Object.keys(client).includes('activateLiveRoom'),'no activate method');ok(!Object.keys(client).includes('deactivateLiveRoom'),'no deactivate method');
for(const call of calls){const env=JSON.parse(call.body);ok(Object.keys(env).length===1&&env.liveRoomRequest,'all calls dedicated envelope')}

if(failed){console.error('LIVE_ROOM_REMOTE_CLIENT_TEST_STATUS=FAIL');console.error('LIVE_ROOM_REMOTE_CLIENT_TEST_TOTAL='+total);console.error('LIVE_ROOM_REMOTE_CLIENT_TEST_FAILED='+failed);process.exit(1)}
console.log('LIVE_ROOM_REMOTE_CLIENT_TEST_STATUS=PASS');console.log('LIVE_ROOM_REMOTE_CLIENT_TEST_TOTAL='+total);console.log('LIVE_ROOM_REMOTE_CLIENT_TEST_FAILED=0');
})().catch(e=>{console.error(e);process.exit(1)});
