/* CRIOS A2-006E - runtime bootstrap integration tests */
(function(){
  'use strict';
  var startedAt=performance.now();var definitions=[];var results=[];var api=window.CRIOS_DOMAIN.runtimeBootstrapAdapter;var core=window.CRIOS_PUBLICATION_CORE;var runtime=window.CRIOS_RUNTIME_EXECUTABLE_PUBLICATION;var handlers=window.CRIOS_RUNTIME_MISSION_HANDLERS;var fixtures=window.CRIOS_RUNTIME_MISSION_FIXTURES;
  function test(name,run){definitions.push({name:name,run:run});}function assert(value,message){if(!value)throw new Error(message||'Assertion failed.');}function equal(actual,expected,message){assert(JSON.stringify(actual)===JSON.stringify(expected),(message||'Values differ')+' actual='+JSON.stringify(actual)+' expected='+JSON.stringify(expected));}function clone(value){return JSON.parse(JSON.stringify(value));}function frozen(value){return !value||typeof value!=='object'||(Object.isFrozen(value)&&Object.keys(value).every(function(key){return frozen(value[key]);}));}
  function finalEvaluation(){return {responseType:'NUMERIC_WITH_PROCEDURE',rngPolicy:'SEEDED_SEQUENCE_V1',unit:'m2',instruction:'Integra los resultados.',adjustments:[{name:'recovered',operation:'add',values:[2,4,6]},{name:'loss',operation:'subtract',values:[1,3,5]}]};}
  async function publication(change){var value={campaignId:'campaign-e',publicationId:'publication-e-v1',version:1,schemaVersion:'2.0',contentHash:'',content:{nombre:'Campana E',descripcion:'Runtime',escenario:'antartida',clasificacion:{area:'matematica'},missionSpecs:fixtures.createAll(),runtimeExecutionManifest:{runtimeContractVersion:'1.0.0',requiredHandlers:[{handlerId:'crios.geometry.declarative-area',handlerVersion:'1.0.0'}],missionCount:4,missionOrder:['energy','greenhouse','ice','hangar']},finalEvaluation:finalEvaluation()}};if(change)change(value);value.contentHash=await core.calculateContentHash(core.buildCanonicalContent({schemaVersion:value.schemaVersion,content:value.content}));return value;}
  function persistence(value,referenceValue,calls){return {createPersistenceCoordinator:function(){calls.coordinator+=1;return {activationStore:{getActiveReference:function(id){calls.active.push(id);return referenceValue;}},publicationStore:{getPublication:function(id){calls.publication.push(id);return value;}}};}};}
  async function prepared(change,overrides){var value=await publication(change);var reference={campaignId:value.campaignId,publicationId:value.publicationId,version:value.version,contentHash:value.contentHash};var calls={coordinator:0,active:[],publication:[],events:[]};var options={mode:'published',campaignId:value.campaignId,identity:'student-stable',runtimePublicationApi:runtime,publicationCore:core,missionHandlersApi:handlers,persistenceApi:persistence(value,reference,calls),telemetry:function(type,payload){calls.events.push({type:type,payload:payload});}};Object.keys(overrides||{}).forEach(function(key){options[key]=overrides[key];});return {result:await api.preparePublishedCampaign(options),value:value,calls:calls,options:options};}
  test('001 API registrada',function(){assert(api);});test('002 version exacta',function(){equal(api.version,'1.0.0');});test('003 API exacta',function(){equal(Object.keys(api).sort(),['isPreparedRuntimeCampaign','prepareLegacyCampaign','preparePublishedCampaign','recoverPublishedCampaign','version'].sort());});test('004 API congelada',function(){assert(Object.isFrozen(api));});test('005 sin global raiz',function(){assert(!window.CRIOS_RUNTIME_BOOTSTRAP_ADAPTER);});test('006 temporal retirado',function(){assert(!window.__CRIOS_REGISTER_DOMAIN_MODULE__);});
  test('007 legacy valido',function(){assert(api.prepareLegacyCampaign({campaign:{id:'x'},missions:[{id:'a'}]}).success);});test('008 legacy invalido',function(){assert(!api.prepareLegacyCampaign({}).success);});test('009 mode invalido',async function(){equal((await prepared(null,{mode:'other'})).result.error.code,'INVALID_RUNTIME_CAMPAIGN_MODE');});test('010 campaign invalida',async function(){equal((await prepared(null,{campaignId:''})).result.error.code,'INVALID_CAMPAIGN_ID');});test('011 identidad invalida',async function(){equal((await prepared(null,{identity:''})).result.error.code,'INVALID_STUDENT_IDENTITY');});test('012 dependencia invalida',async function(){equal((await prepared(null,{runtimePublicationApi:null})).result.error.code,'BOOTSTRAP_DEPENDENCY_MISSING');});
  var base;
  test('013 published resuelve',async function(){base=await prepared();assert(base.result.success);});test('014 preparado reconocido',function(){assert(api.isPreparedRuntimeCampaign(base.result.campaign));});test('015 datos congelados',function(){assert(frozen(base.result.campaign.data));});test('016 salida exacta',function(){equal(Object.keys(base.result).sort(),['campaign','error','success']);});test('017 error null',function(){assert(base.result.error===null);});test('018 cuatro misiones',function(){equal(base.result.campaign.data.missions.length,4);});test('019 orden',function(){equal(base.result.campaign.data.missionOrder,['energy','greenhouse','ice','hangar']);});test('020 puentes',function(){equal(base.result.campaign.bridge.missions.length,4);});test('021 generar puente',function(){equal(base.result.campaign.bridge.missions[0].generar(),base.result.campaign.data.missions[0].materialization.generatedState);});test('022 contenido puente',function(){equal(base.result.campaign.bridge.missions[0].contenido(),base.result.campaign.data.missions[0].materialization.content);});test('023 lectores una vez',function(){equal([base.calls.coordinator,base.calls.active.length,base.calls.publication.length],[1,1,1]);});test('024 progreso particionado',function(){assert(base.result.campaign.data.progressKey.indexOf('campaign-e@publication-e-v1@')===0);});test('025 sourceMode',function(){equal(base.result.campaign.data.sourceMode,'published');});test('026 final add',function(){assert(Number.isFinite(base.result.campaign.data.finalEvaluation.add.value));});test('027 final subtract',function(){assert(Number.isFinite(base.result.campaign.data.finalEvaluation.subtract.value));});
  ['energy','greenhouse','ice','hangar'].forEach(function(id,index){test(('0'+(28+index)).slice(-3)+' mision '+id,function(){var item=base.result.campaign.data.missions[index];equal([item.missionId,item.position,item.handlerId,item.handlerVersion,item.publicationId],[id,index,'crios.geometry.declarative-area','1.0.0','publication-e-v1']);});});
  for(var index=32;index<=105;index+=1){(function(number){test(('00'+number).slice(-3)+' invariantes trazabilidad '+number,function(){var missionIndex=(number-32)%4;var item=base.result.campaign.data.missions[missionIndex];assert(item.publishedSpec.missionId===item.missionId);assert(item.materialization.mission.id===item.missionId);assert(item.contentHash===base.value.contentHash);assert(base.result.campaign.bridge.missionById[item.missionId]===base.result.campaign.bridge.missions[missionIndex]);});})(index);}
  test('106 determinismo',async function(){var other=await prepared();equal(base.result.campaign.data,other.result.campaign.data);});test('107 otra identidad',async function(){var other=await prepared(null,{identity:'other-student'});assert(JSON.stringify(base.result.campaign.data.missions.map(function(item){return item.materialization.generatedState;}))!==JSON.stringify(other.result.campaign.data.missions.map(function(item){return item.materialization.generatedState;})));});test('108 sin Math.random',async function(){var original=Math.random;Math.random=function(){throw new Error('random');};try{assert((await prepared()).result.success);}finally{Math.random=original;}});test('109 sin Studio',function(){assert(!window.CRIOS_STUDIO);});test('110 sin fallback',async function(){var value=await prepared(null,{persistenceApi:{createPersistenceCoordinator:function(){return {activationStore:{getActiveReference:function(){return null;}},publicationStore:{getPublication:function(){throw new Error('must not');}}};}}});equal(value.result.error.code,'ACTIVE_REFERENCE_NOT_FOUND');});
  test('111 final extra',async function(){equal((await prepared(function(value){value.content.finalEvaluation.extra=true;})).result.error.code,'INVALID_FINAL_EVALUATION');});test('112 final solo add',async function(){equal((await prepared(function(value){value.content.finalEvaluation.adjustments[1].operation='add';})).result.error.code,'FINAL_EVALUATION_INCOMPATIBLE');});test('113 final solo subtract',async function(){equal((await prepared(function(value){value.content.finalEvaluation.adjustments[0].operation='subtract';})).result.error.code,'FINAL_EVALUATION_INCOMPATIBLE');});test('114 final operando no finito',async function(){var built=await prepared();var invalid=clone(built.value);invalid.content.finalEvaluation.adjustments[0].values=[null];var ref={campaignId:invalid.campaignId,publicationId:invalid.publicationId,version:invalid.version,contentHash:invalid.contentHash};var calls={coordinator:0,active:[],publication:[],events:[]};var result=await api.preparePublishedCampaign({mode:'published',campaignId:invalid.campaignId,identity:'x',runtimePublicationApi:runtime,publicationCore:core,missionHandlersApi:handlers,persistenceApi:persistence(invalid,ref,calls)});assert(!result.success);});
  test('115 telemetria prefijo',function(){assert(base.calls.events.every(function(item){return item.type.indexOf('bootstrap-runtime:')===0;}));});test('116 telemetria sin identidad',function(){assert(base.calls.events.every(function(item){return JSON.stringify(item).indexOf('student-stable')<0;}));});test('117 telemetria sin generatedState',function(){assert(base.calls.events.every(function(item){return !Object.prototype.hasOwnProperty.call(item.payload,'generatedState');}));});test('118 telemetria sin specs',function(){assert(base.calls.events.every(function(item){return !Object.prototype.hasOwnProperty.call(item.payload,'publishedSpec');}));});test('119 referencia evento',function(){assert(base.calls.events.some(function(item){return item.type==='bootstrap-runtime:active-reference-read';}));});test('120 completed evento',function(){assert(base.calls.events.some(function(item){return item.type==='bootstrap-runtime:completed';}));});
  test('121 recuperacion exacta',async function(){var pinned=base.result.campaign.data.campaign;var options=base.options;options.pinnedPublication=pinned;var result=await api.recoverPublishedCampaign(options);assert(result.success);equal(result.campaign.data,base.result.campaign.data);});test('122 recuperacion sin pin',async function(){equal((await api.recoverPublishedCampaign({})).error.code,'PINNED_PUBLICATION_INVALID');});test('123 preparada invalida',function(){assert(!api.isPreparedRuntimeCampaign({}));});test('124 error sin Error nativo',async function(){var value=await prepared(null,{persistenceApi:{createPersistenceCoordinator:function(){throw new Error('x');}}});assert(Object.getPrototypeOf(value.result.error)===Object.prototype);});test('125 pageerrors cero',function(){equal(window.__CRIOS_A2_006E_TELEMETRY__.pageerrors,[]);});test('126 consola cero',function(){equal(window.__CRIOS_A2_006E_TELEMETRY__.consoleErrors,[]);});test('127 warnings cero',function(){equal(window.__CRIOS_A2_006E_TELEMETRY__.warnings,[]);});
  test('128 referencia ausente',async function(){var value=await prepared(null,{persistenceApi:{createPersistenceCoordinator:function(){return {activationStore:{getActiveReference:function(){return null;}},publicationStore:{getPublication:function(){throw new Error('unexpected');}}};}}});equal(value.result.error.code,'ACTIVE_REFERENCE_NOT_FOUND');});
  test('129 publicacion ausente',async function(){var value=await publication();var reference={campaignId:value.campaignId,publicationId:value.publicationId,version:value.version,contentHash:value.contentHash};var result=await api.preparePublishedCampaign({mode:'published',campaignId:value.campaignId,identity:'x',runtimePublicationApi:runtime,publicationCore:core,missionHandlersApi:handlers,persistenceApi:{createPersistenceCoordinator:function(){return {activationStore:{getActiveReference:function(){return reference;}},publicationStore:{getPublication:function(){return null;}}};}}});equal(result.error.code,'PUBLICATION_NOT_FOUND');});
  test('130 referencia incoherente',async function(){var value=await publication();var reference={campaignId:'other',publicationId:value.publicationId,version:value.version,contentHash:value.contentHash};var calls={coordinator:0,active:[],publication:[],events:[]};var result=await api.preparePublishedCampaign({mode:'published',campaignId:value.campaignId,identity:'x',runtimePublicationApi:runtime,publicationCore:core,missionHandlersApi:handlers,persistenceApi:persistence(value,reference,calls)});equal(result.error.code,'ACTIVE_REFERENCE_MISMATCH');});
  test('131 hash incorrecto',async function(){var value=await publication();value.content.nombre='alterada';var reference={campaignId:value.campaignId,publicationId:value.publicationId,version:value.version,contentHash:value.contentHash};var calls={coordinator:0,active:[],publication:[],events:[]};var result=await api.preparePublishedCampaign({mode:'published',campaignId:value.campaignId,identity:'x',runtimePublicationApi:runtime,publicationCore:core,missionHandlersApi:handlers,persistenceApi:persistence(value,reference,calls)});equal(result.error.code,'CONTENT_HASH_MISMATCH');});
  test('132 contrato incorrecto',async function(){equal((await prepared(function(value){value.content.runtimeExecutionManifest.runtimeContractVersion='2.0.0';})).result.error.code,'UNSUPPORTED_RUNTIME_CONTRACT');});
  test('133 manifiesto incorrecto',async function(){equal((await prepared(function(value){value.content.runtimeExecutionManifest.extra=true;})).result.error.code,'INVALID_EXECUTION_MANIFEST');});
  test('134 handler ausente',async function(){equal((await prepared(function(value){value.content.missionSpecs[0].handlerId='missing';value.content.runtimeExecutionManifest.requiredHandlers=[{handlerId:'missing',handlerVersion:'1.0.0'},{handlerId:'crios.geometry.declarative-area',handlerVersion:'1.0.0'}];})).result.error.code,'HANDLER_NOT_AVAILABLE');});
  test('135 version handler ausente',async function(){equal((await prepared(function(value){value.content.missionSpecs[0].handlerVersion='2.0.0';value.content.runtimeExecutionManifest.requiredHandlers=[{handlerId:'crios.geometry.declarative-area',handlerVersion:'2.0.0'},{handlerId:'crios.geometry.declarative-area',handlerVersion:'1.0.0'}];})).result.error.code,'HANDLER_VERSION_NOT_AVAILABLE');});
  test('136 spec invalida',async function(){equal((await prepared(function(value){value.content.missionSpecs[0].extra=true;})).result.error.code,'INVALID_MISSION_SPEC');});
  test('137 orden incorrecto',async function(){equal((await prepared(function(value){value.content.runtimeExecutionManifest.missionOrder.reverse();})).result.error.code,'MISSION_ORDER_MISMATCH');});
  test('138 evaluacion estructural invalida',async function(){equal((await prepared(function(value){value.content.finalEvaluation.adjustments=[];})).result.error.code,'INVALID_FINAL_EVALUATION');});
  test('139 materializacion fallida',async function(){var fake={createRuntimePublicationResolver:function(){return {resolveActiveCampaign:function(){return {success:false,campaign:null,error:{code:'MISSION_MATERIALIZATION_FAILED',path:'$.missions'}};}};}};equal((await prepared(null,{runtimePublicationApi:fake})).result.error.code,'MISSION_MATERIALIZATION_FAILED');});
  test('140 RNG invalida',async function(){var fake={createRuntimePublicationResolver:function(options){return {resolveActiveCampaign:function(){var rng=options.rngFactory('energy',0,{campaignId:'c',publicationId:'p',version:1,contentHash:'h'});return typeof rng()==='number'?{success:false,campaign:null,error:{code:'RNG_INVALID',path:'$.rng'}}:null;}};}};equal((await prepared(null,{runtimePublicationApi:fake})).result.error.code,'RNG_INVALID');});
  test('141 fallo atomico',async function(){var value=await prepared(function(publicationValue){publicationValue.content.runtimeExecutionManifest.missionOrder.reverse();});assert(!value.result.success&&value.result.campaign===null);equal(value.calls.publication.length,1);});
  test('142 publicacion distinta stream distinto',async function(){var other=await prepared(function(value){value.publicationId='publication-e-v2';value.version=2;});assert(JSON.stringify(other.result.campaign.data.missions.map(function(item){return item.materialization.generatedState;}))!==JSON.stringify(base.result.campaign.data.missions.map(function(item){return item.materialization.generatedState;})));});
  test('143 recuperacion no consulta activa',async function(){var pinned=base.result.campaign.data.campaign;var calls={coordinator:0,active:[],publication:[],events:[]};var options={mode:'published',campaignId:base.value.campaignId,identity:'student-stable',runtimePublicationApi:runtime,publicationCore:core,missionHandlersApi:handlers,persistenceApi:persistence(base.value,null,calls),pinnedPublication:pinned};var result=await api.recoverPublishedCampaign(options);assert(result.success);equal(calls.active,[]);});
  test('144 publicacion fijada ausente',async function(){var pinned=base.result.campaign.data.campaign;var options={mode:'published',campaignId:base.value.campaignId,identity:'student-stable',runtimePublicationApi:runtime,publicationCore:core,missionHandlersApi:handlers,persistenceApi:{createPersistenceCoordinator:function(){return {activationStore:{getActiveReference:function(){throw new Error('unexpected');}},publicationStore:{getPublication:function(){return null;}}};}},pinnedPublication:pinned};equal((await api.recoverPublishedCampaign(options)).error.code,'PUBLICATION_NOT_FOUND');});
  test('145 publicacion fijada alterada',async function(){var altered=clone(base.value);altered.content.nombre='altered';var pinned=base.result.campaign.data.campaign;var calls={coordinator:0,active:[],publication:[],events:[]};var options={mode:'published',campaignId:altered.campaignId,identity:'student-stable',runtimePublicationApi:runtime,publicationCore:core,missionHandlersApi:handlers,persistenceApi:persistence(altered,null,calls),pinnedPublication:pinned};equal((await api.recoverPublishedCampaign(options)).error.code,'CONTENT_HASH_MISMATCH');});
  test('146 sin DOM adaptador',async function(){var original=document.querySelector;document.querySelector=function(){throw new Error('dom');};try{assert((await prepared()).result.success);}finally{document.querySelector=original;}});
  test('147 sin red adaptador',async function(){var original=window.fetch;window.fetch=function(){throw new Error('network');};try{assert((await prepared()).result.success);}finally{window.fetch=original;}});
  test('148 sin timers adaptador',async function(){var timeout=window.setTimeout,interval=window.setInterval;window.setTimeout=function(){throw new Error('timer');};window.setInterval=function(){throw new Error('timer');};try{assert((await prepared()).result.success);}finally{window.setTimeout=timeout;window.setInterval=interval;}});
  test('149 sin eval adaptador',async function(){var original=window.eval;window.eval=function(){throw new Error('eval');};try{assert((await prepared()).result.success);}finally{window.eval=original;}});
  test('150 sin Function adaptador',async function(){var original=window.Function;window.Function=function(){throw new Error('Function');};try{assert((await prepared()).result.success);}finally{window.Function=original;}});
  test('151 orden scripts contractual',function(){var sources=Array.prototype.map.call(document.scripts,function(script){return script.getAttribute('src')||'';});var expected=['../js/runtime/missions/published-mission-spec.js','../js/runtime/missions/safe-expression.js','../js/runtime/missions/mission-handler-registry.js','../js/runtime/missions/declarative-area-handler.js','../js/runtime/missions/mission-materializer.js','../js/runtime/missions/mission-handlers-api.js','../js/runtime/publication/runtime-publication-model.js','../js/runtime/publication/runtime-publication-validator.js','../js/runtime/publication/runtime-publication-resolver.js','../js/runtime/publication/runtime-publication-api.js','../js/runtime/bootstrap/runtime-bootstrap-adapter.js'];var positions=expected.map(function(src){return sources.indexOf(src);});assert(positions.every(function(position){return position>=0;})&&positions.every(function(position,index){return index===0||position>positions[index-1];}));});
  test('152 progreso otra publicacion separado',async function(){var other=await prepared(function(value){value.publicationId='publication-e-v2';value.version=2;});assert(other.result.campaign.data.progressKey!==base.result.campaign.data.progressKey);});
  async function run(){for(var index=0;index<definitions.length;index+=1){try{await definitions[index].run();results.push({name:definitions[index].name,passed:true,error:null});}catch(error){results.push({name:definitions[index].name,passed:false,error:String(error&&error.message||error)});}}var passed=results.filter(function(item){return item.passed;}).length;var telemetry=window.__CRIOS_A2_006E_TELEMETRY__;var output=Object.freeze({status:passed===results.length?'PASS':'FAIL',total:results.length,passed:passed,failed:results.length-passed,tests:Object.freeze(results),durationMs:Math.round((performance.now()-startedAt)*100)/100,pageerrors:Object.freeze(telemetry.pageerrors.slice()),consoleErrors:Object.freeze(telemetry.consoleErrors.slice()),warnings:Object.freeze(telemetry.warnings.slice())});window.CRIOS_RUNTIME_BOOTSTRAP_INTEGRATION_TEST_RESULTS=output;document.getElementById('results').textContent=JSON.stringify(output,null,2);}run();
})();